# Generated by Django 4.1.4 on 2023-12-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('blood_presure', models.CharField(max_length=100)),
                ('blood_sugar', models.IntegerField()),
            ],
        ),
    ]
