# Generated by Django 4.1.4 on 2023-12-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthhistory',
            name='blood_presure',
        ),
        migrations.RemoveField(
            model_name='healthhistory',
            name='blood_sugar',
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='BPM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='SPO2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
