# Generated by Django 3.1 on 2023-12-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_healthhistory_blood_presure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
