# Generated by Django 5.0 on 2023-12-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20231219_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthhistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
