# Generated by Django 5.0 on 2024-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_healthhistory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthhistory", name="location_x", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="healthhistory", name="location_y", field=models.FloatField(),
        ),
    ]
